social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('update/<str:pk>/', views.update, name='update'),
    path('delete/<str:pk>/', views.delete, name='delete'),
]

todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=255)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

todo/forms.py
from django import forms
from django.forms import ModelForm

from . models import *

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

todo/views.py
from django.shortcuts import render, redirect
from . models import *
from .forms import *

# Create your views here.

def index(request):
    todos = Todo.objects.all()
    
    form = TodoForm()

    if request.method == 'POST':
        form = TodoForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect('/')
    return render(request, template_name='todo/index.html', context={'todos': todos, 'form': form})


def update(request, pk):
    todo = Todo.objects.get(id=pk)

    form = TodoForm(instance=todo)

    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('/')

    return render(request, template_name='todo/update.html', context={'form': form})

def delete(request, pk):
    item = Todo.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/')
    return render(request, template_name='todo/delete.html', context={'item': item})

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Welcome</title>
</head>
<body>
    <nav class="py-6 px-6 flex items-center justify-between bg-gray-900">
        <a href="/" class="text-green-300 font-semibold">Schedule</a>

        <div class="space-x-4">
            <a href="#" class="text-green-300 font-semibold hover:text-cyan-500">New</a>
            <a href="#" class="text-green-300 font-semibold hover:text-cyan-500">Browse</a>
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
        
    
    <footer class="py-6 px-6 flex justify-between bg-gray-900">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">Make schedules with ease
            </p>
        </div>
        
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

todo/templates/todo/delete.html
<h3>Are you sure you want to delete "{{ item }}"?</h3>

<a href="{% url 'todo:index' %}" class="mb-3 bg-green-400 text-white rounded-xl">Cancel</a>

<form method="post" action=".">
    {% csrf_token %}
    <input type="button">
    <button class="mt-3 mb-3 py-2 px-4 bg-green-600 hover:bg-green-300 text-white rounded-xl">Confirm</button>
</form>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block title %}Home{% endblock %}



{% block content %}
<h1 class="mt-4 text-white bg-blue-500 rounded-xl">Schedule Made Simple</h1>


<br>

<form method="post" action="." class="mb-4 mt-3">
    {% csrf_token %}
 
    Title:{{ form.title }}
    <input type="button">
      <button class="mt-2 mb-2 py-1 px-2 bg-green-600 hover:bg-green-300 text-white rounded-xl">Create Todo</button>
    </form>
    {% for todo in todos %}
        <div>
            <br>
            <a href="{% url 'todo:update' todo.id %}" class="mb-4 mt-4 bg-green-400 text-white rounded-xl">Update</a>
            <a href="{% url 'todo:delete' todo.id %}" class="mb-4 mt-4 bg-red-400 text-white rounded-xl">Delete</a>
            
            {% if task.complete == True %}
            <strike>{{ todo }}</strike>
            {% else %}
            <span>{{ todo }}</span>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}


todo/templates/todo/update.html
{% extends 'todo/base.html' %}

{% block title %}Update{% endblock %}

{% block content %}
    <form method="post" action=".">
        {% csrf_token %}

        {{ form }}
        <input type="button">
      <button class="mt-3 mb-3 py-2 px-4 bg-green-600 hover:bg-green-300 text-white rounded-xl">Update</button>
    </form>
{% endblock %}